using System;
using System.Collections.Generic;
using System.IO;

//This file is auto-generated by the 'SecureEmail.CodeGenerator'. Do not change.
namespace HelianzBusiness {
	///<summary></summary>
	public class GetAccountGuarantorResponse {

		///<summary></summary>
		public long AccountGuarantorNum { get; set; }

		///<summary></summary>
		public string Description { get; set; }

		///<summary></summary>
		public string ExternalID { get; set; }

	}
}
