using System;
using System.Collections.Generic;
using System.IO;

//This file is auto-generated by the 'SecureEmail.CodeGenerator'. Do not change.
namespace HelianzBusiness {
	///<summary></summary>
	public class ResetAccountPasswordResponse {

		///<summary>The new guid for the password.</summary>
		public string AccountSecret { get; set; }

	}
}
