using System;
using System.Diagnostics;
using System.IO;
using System.Text;
using System.Web.Services.Protocols;

namespace HelianzBusiness {
	[AttributeUsage(AttributeTargets.Method)]
	public class SoapLoggingAttribute : SoapExtensionAttribute {
		private int _priority=1;
		public override Type ExtensionType => typeof(SoapLoggingExtension);
		public override int Priority {
			get => _priority;
			set => _priority=value;
		}
	}

	///<summary>SoapExtension that intercepts and logs raw SOAP XML envelopes for requests and responses.</summary>
	public class SoapLoggingExtension : SoapExtension {
		private Stream _oldStream;
		private Stream _newStream;
		private Stopwatch _stopwatch;

		public override Stream ChainStream(Stream stream) {
			_oldStream=stream;
			_newStream=new MemoryStream();
			return _newStream;
		}

		public override object GetInitializer(LogicalMethodInfo methodInfo,SoapExtensionAttribute attribute) {
			return null;
		}

		public override object GetInitializer(Type WebServiceType) {
			return null;
		}

		public override void Initialize(object initializer) {
		}

		public override void ProcessMessage(SoapMessage message) {
			switch(message.Stage) {
				case SoapMessageStage.BeforeSerialize:
					_stopwatch=Stopwatch.StartNew();
					break;
				case SoapMessageStage.AfterSerialize:
					LogSoapRequest(message);
					break;
				case SoapMessageStage.BeforeDeserialize:
					LogSoapResponse(message);
					break;
				case SoapMessageStage.AfterDeserialize:
					LogSoapResult(message);
					break;
			}
		}

		private void LogSoapRequest(SoapMessage message) {
			try {
				_newStream.Position=0;
				using(StreamReader reader=new StreamReader(_newStream,Encoding.UTF8,false,1024,true)) {
					string soapXml=reader.ReadToEnd();
					long callId=SoapLogger.CurrentCallId;
					SoapLogger.LogRawSoapRequest(callId,soapXml,message.Url);
				}
				_newStream.Position=0;
				CopyStream(_newStream,_oldStream);
			}
			catch(Exception ex) {
				SoapLogger.LogError(SoapLogger.CurrentCallId,"SoapExtension.AfterSerialize",message.MethodInfo?.Name,ex);
			}
		}

		private void LogSoapResponse(SoapMessage message) {
			try {
				CopyStream(_oldStream,_newStream);
				_newStream.Position=0;
				using(StreamReader reader=new StreamReader(_newStream,Encoding.UTF8,false,1024,true)) {
					string soapXml=reader.ReadToEnd();
					// Auto-fix utf-16 declaration if generated by server
					if(soapXml.Contains("encoding=\"utf-16\"")) {
						soapXml=soapXml.Replace("encoding=\"utf-16\"","encoding=\"utf-8\"");
						byte[] fixedBytes=Encoding.UTF8.GetBytes(soapXml);
						_newStream.SetLength(0);
						_newStream.Write(fixedBytes,0,fixedBytes.Length);
					}
					long elapsed=_stopwatch?.ElapsedMilliseconds ?? 0;
					long callId=SoapLogger.CurrentCallId;
					SoapLogger.LogRawSoapResponse(callId,soapXml,elapsed);
				}
				_newStream.Position=0;
			}
			catch(Exception ex) {
				SoapLogger.LogError(SoapLogger.CurrentCallId,"SoapExtension.BeforeDeserialize",message.MethodInfo?.Name,ex);
			}
		}

		private void LogSoapResult(SoapMessage message) {
			if(message.Exception!=null) {
				SoapLogger.LogError(SoapLogger.CurrentCallId,"SoapExtension.AfterDeserialize",message.MethodInfo?.Name,message.Exception);
			}
		}

		private static void CopyStream(Stream from,Stream to) {
			byte[] buffer=new byte[4096];
			int count;
			while((count=from.Read(buffer,0,buffer.Length))>0) {
				to.Write(buffer,0,count);
			}
			to.Flush();
		}
	}
}
