//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelianzBusiness.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/HelianzServer/ServiceMain.asmx")]
        public string HelianzBusiness_HelianzServer_ServiceMain {
            get {
                return ((string)(this["HelianzBusiness_HelianzServer_ServiceMain"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/HelianzWebServiceHQ/WebServiceMainHQ.asmx")]
        public string HelianzBusiness_WebServiceMainHQ_WebServiceMainHQ {
            get {
                return ((string)(this["HelianzBusiness_WebServiceMainHQ_WebServiceMainHQ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://50.201.161.44:1942/WebServiceCustomerUpdates/Service1.asmx")]
        public string HelianzBusiness_customerupdates_Service1 {
            get {
                return ((string)(this["HelianzBusiness_customerupdates_Service1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:3824/Service1.asmx")]
        public string HelianzBusiness_localhost_Service1 {
            get {
                return ((string)(this["HelianzBusiness_localhost_Service1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.dentalxchange.com:443/dws/DwsService")]
        public string HelianzBusiness_Dentalxchange2016_DwsService {
            get {
                return ((string)(this["HelianzBusiness_Dentalxchange2016_DwsService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.dentalxchange.com/dws/services/dciservice.svl")]
        public string HelianzBusiness_com_dentalxchange_webservices_WebServiceService {
            get {
                return ((string)(this["HelianzBusiness_com_dentalxchange_webservices_WebServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://its.changehealthcare.com/ITS/ITSWS.asmx")]
        public string HelianzBusiness_EmdeonITS_ITSWS {
            get {
                return ((string)(this["HelianzBusiness_EmdeonITS_ITSWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://my.dosespot.com/api/12/api.asmx")]
        public string HelianzBusiness_com_dosespot_staging_my_API {
            get {
                return ((string)(this["HelianzBusiness_com_dosespot_staging_my_API"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://prelive2.dentalxchange.com:443/merchant/MerchantService")]
        public string HelianzBusiness_PayConnectService_MerchantService {
            get {
                return ((string)(this["HelianzBusiness_PayConnectService_MerchantService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://prelive2.dentalxchange.com:443/dea/DeaPartnerService")]
        public string HelianzBusiness_DentalxchangePartnerService_DeaPartnerService {
            get {
                return ((string)(this["HelianzBusiness_DentalxchangePartnerService_DeaPartnerService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:2923/SheetsSynch.asmx")]
        public string HelianzBusiness_SheetsSynch_SheetsSynch {
            get {
                return ((string)(this["HelianzBusiness_SheetsSynch_SheetsSynch"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HelianzBusiness_WebServiceMainHq_Mock {
            get {
                return ((bool)(this["HelianzBusiness_WebServiceMainHq_Mock"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://secure.newcropaccounts.com/v7/WebServices/Update1.asmx")]
        public string HelianzBusiness_NewCrop_Update1 {
            get {
                return ((string)(this["HelianzBusiness_NewCrop_Update1"]));
            }
        }
    }
}
