//This file is automatically generated.
//Do not attempt to make changes to this file because the changes will be erased and overwritten.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Linq;

namespace HelianzBusiness.Crud {
	public class MidtransTransactionCrud {
		///<summary>Gets one MidtransTransaction object from the database using the primary key.  Returns null if not found.</summary>
		public static MidtransTransaction SelectOne(long midtransTransactionNum) {
			string command="SELECT * FROM midtranstransaction "
				+"WHERE MidtransTransactionNum = "+POut.Long(midtransTransactionNum);
			List<MidtransTransaction> list=TableToList(Db.GetTable(command));
			if(list.Count==0) {
				return null;
			}
			return list[0];
		}

		///<summary>Gets one MidtransTransaction object from the database using a query.</summary>
		public static MidtransTransaction SelectOne(string command) {
			if(RemotingClient.MiddleTierRole==MiddleTierRole.ClientMT) {
				throw new ApplicationException("Not allowed to send sql directly.  Rewrite the calling class to not use this query:\r\n"+command);
			}
			List<MidtransTransaction> list=TableToList(Db.GetTable(command));
			if(list.Count==0) {
				return null;
			}
			return list[0];
		}

		///<summary>Gets a list of MidtransTransaction objects from the database using a query.</summary>
		public static List<MidtransTransaction> SelectMany(string command) {
			if(RemotingClient.MiddleTierRole==MiddleTierRole.ClientMT) {
				throw new ApplicationException("Not allowed to send sql directly.  Rewrite the calling class to not use this query:\r\n"+command);
			}
			List<MidtransTransaction> list=TableToList(Db.GetTable(command));
			return list;
		}

		///<summary>Converts a DataTable to a list of objects.</summary>
		public static List<MidtransTransaction> TableToList(DataTable table) {
			List<MidtransTransaction> retVal=new List<MidtransTransaction>();
			MidtransTransaction midtransTransaction;
			foreach(DataRow row in table.Rows) {
				midtransTransaction=new MidtransTransaction();
				midtransTransaction.MidtransTransactionNum= PIn.Long  (row["MidtransTransactionNum"].ToString());
				midtransTransaction.PatNum                = PIn.Long  (row["PatNum"].ToString());
				midtransTransaction.PayNum                = PIn.Long  (row["PayNum"].ToString());
				midtransTransaction.OrderId               = PIn.String(row["OrderId"].ToString());
				midtransTransaction.TransactionId         = PIn.String(row["TransactionId"].ToString());
				midtransTransaction.PaymentType           = PIn.String(row["PaymentType"].ToString());
				midtransTransaction.GrossAmount           = PIn.Long  (row["GrossAmount"].ToString());
				midtransTransaction.QrCodeUrl             = PIn.String(row["QrCodeUrl"].ToString());
				midtransTransaction.StatusUrl             = PIn.String(row["StatusUrl"].ToString());
				string transactionStatus=row["TransactionStatus"].ToString();
				if(transactionStatus=="") {
					midtransTransaction.TransactionStatus=(HelianzBusiness.MidtransTransactionStatus)0;
				}
				else try {
					midtransTransaction.TransactionStatus=(HelianzBusiness.MidtransTransactionStatus)Enum.Parse(typeof(HelianzBusiness.MidtransTransactionStatus),transactionStatus);
				}
				catch {
					midtransTransaction.TransactionStatus=(HelianzBusiness.MidtransTransactionStatus)0;
				}
				midtransTransaction.LastResponseJson      = PIn.String(row["LastResponseJson"].ToString());
				midtransTransaction.DateTimeCreated       = PIn.DateT (row["DateTimeCreated"].ToString());
				midtransTransaction.DateTimeSettled       = PIn.DateT (row["DateTimeSettled"].ToString());
				midtransTransaction.ClinicNum             = PIn.Long  (row["ClinicNum"].ToString());
				midtransTransaction.PayNote               = PIn.String(row["PayNote"].ToString());
				retVal.Add(midtransTransaction);
			}
			return retVal;
		}

		///<summary>Inserts one MidtransTransaction into the database.  Returns the new priKey.</summary>
		public static long Insert(MidtransTransaction midtransTransaction) {
			return Insert(midtransTransaction,false);
		}

		///<summary>Inserts one MidtransTransaction into the database.  Provides option to use the existing priKey.</summary>
		public static long Insert(MidtransTransaction midtransTransaction,bool useExistingPK) {
			if(!useExistingPK && PrefC.RandomKeys) {
				midtransTransaction.MidtransTransactionNum=ReplicationServers.GetKey("midtranstransaction","MidtransTransactionNum");
			}
			string command="INSERT INTO midtranstransaction (";
			if(useExistingPK || PrefC.RandomKeys) {
				command+="MidtransTransactionNum,";
			}
			command+="PatNum,PayNum,OrderId,TransactionId,PaymentType,GrossAmount,QrCodeUrl,StatusUrl,"
				+"TransactionStatus,LastResponseJson,DateTimeCreated,DateTimeSettled,ClinicNum,PayNote) VALUES(";
			if(useExistingPK || PrefC.RandomKeys) {
				command+=POut.Long(midtransTransaction.MidtransTransactionNum)+",";
			}
			command+=
				     POut.Long  (midtransTransaction.PatNum)+","
				+    POut.Long  (midtransTransaction.PayNum)+","
				+"'"+POut.String(midtransTransaction.OrderId)+"',"
				+"'"+POut.String(midtransTransaction.TransactionId)+"',"
				+"'"+POut.String(midtransTransaction.PaymentType)+"',"
				+    POut.Long  (midtransTransaction.GrossAmount)+","
				+"'"+POut.String(midtransTransaction.QrCodeUrl)+"',"
				+"'"+POut.String(midtransTransaction.StatusUrl)+"',"
				+"'"+POut.String(midtransTransaction.TransactionStatus.ToString())+"',"
				+"'"+POut.String(midtransTransaction.LastResponseJson)+"',"
				+    POut.DateT (midtransTransaction.DateTimeCreated)+","
				+    POut.DateT (midtransTransaction.DateTimeSettled)+","
				+    POut.Long  (midtransTransaction.ClinicNum)+","
				+"'"+POut.String(midtransTransaction.PayNote)+"')";
			if(useExistingPK || PrefC.RandomKeys) {
				Db.NonQ(command);
			}
			else {
				midtransTransaction.MidtransTransactionNum=Db.NonQ(command,true,"MidtransTransactionNum","midtranstransaction");
			}
			return midtransTransaction.MidtransTransactionNum;
		}

		///<summary>Updates one MidtransTransaction in the database.</summary>
		public static void Update(MidtransTransaction midtransTransaction) {
			string command="UPDATE midtranstransaction SET "
				+"PatNum            =  " +POut.Long  (midtransTransaction.PatNum)+", "
				+"PayNum            =  " +POut.Long  (midtransTransaction.PayNum)+", "
				+"OrderId           = '"+POut.String(midtransTransaction.OrderId)+"', "
				+"TransactionId     = '"+POut.String(midtransTransaction.TransactionId)+"', "
				+"PaymentType       = '"+POut.String(midtransTransaction.PaymentType)+"', "
				+"GrossAmount       =  " +POut.Long  (midtransTransaction.GrossAmount)+", "
				+"QrCodeUrl         = '"+POut.String(midtransTransaction.QrCodeUrl)+"', "
				+"StatusUrl         = '"+POut.String(midtransTransaction.StatusUrl)+"', "
				+"TransactionStatus = '"+POut.String(midtransTransaction.TransactionStatus.ToString())+"', "
				+"LastResponseJson  = '"+POut.String(midtransTransaction.LastResponseJson)+"', "
				+"DateTimeCreated   =  " +POut.DateT (midtransTransaction.DateTimeCreated)+", "
				+"DateTimeSettled   =  " +POut.DateT (midtransTransaction.DateTimeSettled)+", "
				+"ClinicNum         =  " +POut.Long  (midtransTransaction.ClinicNum)+", "
				+"PayNote           = '"+POut.String(midtransTransaction.PayNote)+"' "
				+"WHERE MidtransTransactionNum = "+POut.Long(midtransTransaction.MidtransTransactionNum);
			Db.NonQ(command);
		}

		///<summary>Deletes one MidtransTransaction from the database.</summary>
		public static void Delete(long midtransTransactionNum) {
			string command="DELETE FROM midtranstransaction WHERE MidtransTransactionNum = "+POut.Long(midtransTransactionNum);
			Db.NonQ(command);
		}
	}
}
