//This file is automatically generated.
//Do not attempt to make changes to this file because the changes will be erased and overwritten.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Linq;

namespace HelianzBusiness.Crud {
	public class MidtransConfigCrud {
		///<summary>Gets one MidtransConfig object from the database using the primary key.  Returns null if not found.</summary>
		public static MidtransConfig SelectOne(long midtransConfigNum) {
			string command="SELECT * FROM midtransconfig "
				+"WHERE MidtransConfigNum = "+POut.Long(midtransConfigNum);
			List<MidtransConfig> list=TableToList(Db.GetTable(command));
			if(list.Count==0) {
				return null;
			}
			return list[0];
		}

		///<summary>Gets one MidtransConfig object from the database using a query.</summary>
		public static MidtransConfig SelectOne(string command) {
			if(RemotingClient.MiddleTierRole==MiddleTierRole.ClientMT) {
				throw new ApplicationException("Not allowed to send sql directly.  Rewrite the calling class to not use this query:\r\n"+command);
			}
			List<MidtransConfig> list=TableToList(Db.GetTable(command));
			if(list.Count==0) {
				return null;
			}
			return list[0];
		}

		///<summary>Gets a list of MidtransConfig objects from the database using a query.</summary>
		public static List<MidtransConfig> SelectMany(string command) {
			if(RemotingClient.MiddleTierRole==MiddleTierRole.ClientMT) {
				throw new ApplicationException("Not allowed to send sql directly.  Rewrite the calling class to not use this query:\r\n"+command);
			}
			List<MidtransConfig> list=TableToList(Db.GetTable(command));
			return list;
		}

		///<summary>Converts a DataTable to a list of objects.</summary>
		public static List<MidtransConfig> TableToList(DataTable table) {
			List<MidtransConfig> retVal=new List<MidtransConfig>();
			MidtransConfig midtransConfig;
			foreach(DataRow row in table.Rows) {
				midtransConfig=new MidtransConfig();
				midtransConfig.MidtransConfigNum= PIn.Long  (row["MidtransConfigNum"].ToString());
				midtransConfig.ServerKey        = PIn.String(row["ServerKey"].ToString());
				midtransConfig.ClientKey        = PIn.String(row["ClientKey"].ToString());
				string environment=row["Environment"].ToString();
				if(environment=="") {
					midtransConfig.Environment=(HelianzBusiness.MidtransEnvironment)0;
				}
				else try {
					midtransConfig.Environment=(HelianzBusiness.MidtransEnvironment)Enum.Parse(typeof(HelianzBusiness.MidtransEnvironment),environment);
				}
				catch {
					midtransConfig.Environment=(HelianzBusiness.MidtransEnvironment)0;
				}
				midtransConfig.IsEnabled        = PIn.Bool  (row["IsEnabled"].ToString());
				midtransConfig.ClinicNum        = PIn.Long  (row["ClinicNum"].ToString());
				midtransConfig.MerchantName     = PIn.String(row["MerchantName"].ToString());
				midtransConfig.PayTypeDefNum    = PIn.Long  (row["PayTypeDefNum"].ToString());
				midtransConfig.Note             = PIn.String(row["Note"].ToString());
				retVal.Add(midtransConfig);
			}
			return retVal;
		}

		///<summary>Inserts one MidtransConfig into the database.  Returns the new priKey.</summary>
		public static long Insert(MidtransConfig midtransConfig) {
			return Insert(midtransConfig,false);
		}

		///<summary>Inserts one MidtransConfig into the database.  Provides option to use the existing priKey.</summary>
		public static long Insert(MidtransConfig midtransConfig,bool useExistingPK) {
			if(!useExistingPK && PrefC.RandomKeys) {
				midtransConfig.MidtransConfigNum=ReplicationServers.GetKey("midtransconfig","MidtransConfigNum");
			}
			string command="INSERT INTO midtransconfig (";
			if(useExistingPK || PrefC.RandomKeys) {
				command+="MidtransConfigNum,";
			}
			command+="ServerKey,ClientKey,Environment,IsEnabled,ClinicNum,MerchantName,PayTypeDefNum,Note) VALUES(";
			if(useExistingPK || PrefC.RandomKeys) {
				command+=POut.Long(midtransConfig.MidtransConfigNum)+",";
			}
			command+=
				 "'"+POut.String(midtransConfig.ServerKey)+"',"
				+"'"+POut.String(midtransConfig.ClientKey)+"',"
				+"'"+POut.String(midtransConfig.Environment.ToString())+"',"
				+    POut.Bool  (midtransConfig.IsEnabled)+","
				+    POut.Long  (midtransConfig.ClinicNum)+","
				+"'"+POut.String(midtransConfig.MerchantName)+"',"				+    POut.Long  (midtransConfig.PayTypeDefNum)+","				+"'"+POut.String(midtransConfig.Note)+"')";
			if(useExistingPK || PrefC.RandomKeys) {
				Db.NonQ(command);
			}
			else {
				midtransConfig.MidtransConfigNum=Db.NonQ(command,true,"MidtransConfigNum","midtransconfig");
			}
			return midtransConfig.MidtransConfigNum;
		}

		///<summary>Updates one MidtransConfig in the database.</summary>
		public static void Update(MidtransConfig midtransConfig) {
			string command="UPDATE midtransconfig SET "
				+"ServerKey    = '"+POut.String(midtransConfig.ServerKey)+"', "
				+"ClientKey    = '"+POut.String(midtransConfig.ClientKey)+"', "
				+"Environment  = '"+POut.String(midtransConfig.Environment.ToString())+"', "
				+"IsEnabled    =  " +POut.Bool  (midtransConfig.IsEnabled)+", "
				+"ClinicNum    =  " +POut.Long  (midtransConfig.ClinicNum)+", "
				+"MerchantName = '"+POut.String(midtransConfig.MerchantName)+"', "				+"PayTypeDefNum=  " +POut.Long  (midtransConfig.PayTypeDefNum)+", "				+"Note         = '"+POut.String(midtransConfig.Note)+"' "
				+"WHERE MidtransConfigNum = "+POut.Long(midtransConfig.MidtransConfigNum);
			Db.NonQ(command);
		}

		///<summary>Deletes one MidtransConfig from the database.</summary>
		public static void Delete(long midtransConfigNum) {
			string command="DELETE FROM midtransconfig WHERE MidtransConfigNum = "+POut.Long(midtransConfigNum);
			Db.NonQ(command);
		}
	}
}
