//This file is automatically generated.
//Do not attempt to make changes to this file because the changes will be erased and overwritten.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Linq;

namespace HelianzBusiness.Crud {
	public class SatuSehatStatusCrud {
		///<summary>Gets one SatuSehatStatus object from the database using the primary key.  Returns null if not found.</summary>
		public static SatuSehatStatus SelectOne(long satuSehatStatusNum) {
			string command="SELECT * FROM satusehatstatus "
				+"WHERE SatuSehatStatusNum = "+POut.Long(satuSehatStatusNum);
			List<SatuSehatStatus> list=TableToList(Db.GetTable(command));
			if(list.Count==0) {
				return null;
			}
			return list[0];
		}

		///<summary>Gets one SatuSehatStatus object from the database using a query.</summary>
		public static SatuSehatStatus SelectOne(string command) {
			if(RemotingClient.MiddleTierRole==MiddleTierRole.ClientMT) {
				throw new ApplicationException("Not allowed to send sql directly.  Rewrite the calling class to not use this query:\r\n"+command);
			}
			List<SatuSehatStatus> list=TableToList(Db.GetTable(command));
			if(list.Count==0) {
				return null;
			}
			return list[0];
		}

		///<summary>Gets a list of SatuSehatStatus objects from the database using a query.</summary>
		public static List<SatuSehatStatus> SelectMany(string command) {
			if(RemotingClient.MiddleTierRole==MiddleTierRole.ClientMT) {
				throw new ApplicationException("Not allowed to send sql directly.  Rewrite the calling class to not use this query:\r\n"+command);
			}
			List<SatuSehatStatus> list=TableToList(Db.GetTable(command));
			return list;
		}

		///<summary>Converts a DataTable to a list of objects.</summary>
		public static List<SatuSehatStatus> TableToList(DataTable table) {
			List<SatuSehatStatus> retVal=new List<SatuSehatStatus>();
			SatuSehatStatus satuSehatStatus;
			foreach(DataRow row in table.Rows) {
				satuSehatStatus=new SatuSehatStatus();
				satuSehatStatus.SatuSehatStatusNum = PIn.Long  (row["SatuSehatStatusNum"].ToString());
				satuSehatStatus.PatNum             = PIn.Long  (row["PatNum"].ToString());
				string resourceType=row["ResourceType"].ToString();
				if(resourceType=="") {
					satuSehatStatus.ResourceType=(HelianzBusiness.SatuSehatResourceType)0;
				}
				else try {
					satuSehatStatus.ResourceType=(HelianzBusiness.SatuSehatResourceType)Enum.Parse(typeof(HelianzBusiness.SatuSehatResourceType),resourceType);
				}
				catch {
					satuSehatStatus.ResourceType=(HelianzBusiness.SatuSehatResourceType)0;
				}
				satuSehatStatus.LocalResourceId    = PIn.Long  (row["LocalResourceId"].ToString());
				satuSehatStatus.IhsId              = PIn.String(row["IhsId"].ToString());
				string syncStatus=row["SyncStatus"].ToString();
				if(syncStatus=="") {
					satuSehatStatus.SyncStatus=(HelianzBusiness.SatuSehatSyncStatus)0;
				}
				else try {
					satuSehatStatus.SyncStatus=(HelianzBusiness.SatuSehatSyncStatus)Enum.Parse(typeof(HelianzBusiness.SatuSehatSyncStatus),syncStatus);
				}
				catch {
					satuSehatStatus.SyncStatus=(HelianzBusiness.SatuSehatSyncStatus)0;
				}
				satuSehatStatus.LastSyncAt         = PIn.DateT (row["LastSyncAt"].ToString());
				satuSehatStatus.ErrorMessage       = PIn.String(row["ErrorMessage"].ToString());
				satuSehatStatus.RetryCount         = PIn.Int   (row["RetryCount"].ToString());
				satuSehatStatus.DateTimeInsert     = PIn.DateT (row["DateTimeInsert"].ToString());
				retVal.Add(satuSehatStatus);
			}
			return retVal;
		}

		///<summary>Converts a list of SatuSehatStatus into a DataTable.</summary>
		public static DataTable ListToTable(List<SatuSehatStatus> listSatuSehatStatuses,string tableName="") {
			if(string.IsNullOrEmpty(tableName)) {
				tableName="SatuSehatStatus";
			}
			DataTable table=new DataTable(tableName);
			table.Columns.Add("SatuSehatStatusNum");
			table.Columns.Add("PatNum");
			table.Columns.Add("ResourceType");
			table.Columns.Add("LocalResourceId");
			table.Columns.Add("IhsId");
			table.Columns.Add("SyncStatus");
			table.Columns.Add("LastSyncAt");
			table.Columns.Add("ErrorMessage");
			table.Columns.Add("RetryCount");
			table.Columns.Add("DateTimeInsert");
			foreach(SatuSehatStatus satuSehatStatus in listSatuSehatStatuses) {
				table.Rows.Add(new object[] {
					POut.Long  (satuSehatStatus.SatuSehatStatusNum),
					POut.Long  (satuSehatStatus.PatNum),
					POut.String(satuSehatStatus.ResourceType.ToString()),
					POut.Long  (satuSehatStatus.LocalResourceId),
					POut.String(satuSehatStatus.IhsId),
					POut.String(satuSehatStatus.SyncStatus.ToString()),
					POut.DateT (satuSehatStatus.LastSyncAt,false),
					POut.String(satuSehatStatus.ErrorMessage),
					POut.Int   (satuSehatStatus.RetryCount),
					POut.DateT (satuSehatStatus.DateTimeInsert,false),
				});
			}
			return table;
		}

		///<summary>Inserts one SatuSehatStatus into the database.  Returns the new priKey.</summary>
		public static long Insert(SatuSehatStatus satuSehatStatus) {
			return Insert(satuSehatStatus,false);
		}

		///<summary>Inserts one SatuSehatStatus into the database.  Provides option to use the existing priKey.</summary>
		public static long Insert(SatuSehatStatus satuSehatStatus,bool useExistingPK) {
			if(!useExistingPK && PrefC.RandomKeys) {
				satuSehatStatus.SatuSehatStatusNum=ReplicationServers.GetKey("satusehatstatus","SatuSehatStatusNum");
			}
			string command="INSERT INTO satusehatstatus (";
			if(useExistingPK || PrefC.RandomKeys) {
				command+="SatuSehatStatusNum,";
			}
			command+="PatNum,ResourceType,LocalResourceId,IhsId,SyncStatus,LastSyncAt,ErrorMessage,RetryCount,DateTimeInsert) VALUES(";
			if(useExistingPK || PrefC.RandomKeys) {
				command+=POut.Long(satuSehatStatus.SatuSehatStatusNum)+",";
			}
			command+=
				     POut.Long  (satuSehatStatus.PatNum)+","
				+"'"+POut.String(satuSehatStatus.ResourceType.ToString())+"',"
				+    POut.Long  (satuSehatStatus.LocalResourceId)+","
				+"'"+POut.String(satuSehatStatus.IhsId)+"',"
				+"'"+POut.String(satuSehatStatus.SyncStatus.ToString())+"',"
				+    POut.DateT (satuSehatStatus.LastSyncAt)+","
				+"'"+POut.String(satuSehatStatus.ErrorMessage)+"',"
				+    POut.Int   (satuSehatStatus.RetryCount)+","
				+    POut.DateT (satuSehatStatus.DateTimeInsert)+")";
			if(useExistingPK || PrefC.RandomKeys) {
				Db.NonQ(command);
			}
			else {
				satuSehatStatus.SatuSehatStatusNum=Db.NonQ(command,true,"SatuSehatStatusNum","satuSehatStatus");
			}
			return satuSehatStatus.SatuSehatStatusNum;
		}

		///<summary>Inserts one SatuSehatStatus into the database.  Returns the new priKey.  Doesn't use the cache.</summary>
		public static long InsertNoCache(SatuSehatStatus satuSehatStatus) {
			return InsertNoCache(satuSehatStatus,false);
		}

		///<summary>Inserts one SatuSehatStatus into the database.  Provides option to use the existing priKey.  Doesn't use the cache.</summary>
		public static long InsertNoCache(SatuSehatStatus satuSehatStatus,bool useExistingPK) {
			bool isRandomKeys=Prefs.GetBoolNoCache(PrefName.RandomPrimaryKeys);
			string command="INSERT INTO satusehatstatus (";
			if(!useExistingPK && isRandomKeys) {
				satuSehatStatus.SatuSehatStatusNum=ReplicationServers.GetKeyNoCache("satusehatstatus","SatuSehatStatusNum");
			}
			if(isRandomKeys || useExistingPK) {
				command+="SatuSehatStatusNum,";
			}
			command+="PatNum,ResourceType,LocalResourceId,IhsId,SyncStatus,LastSyncAt,ErrorMessage,RetryCount,DateTimeInsert) VALUES(";
			if(isRandomKeys || useExistingPK) {
				command+=POut.Long(satuSehatStatus.SatuSehatStatusNum)+",";
			}
			command+=
				     POut.Long  (satuSehatStatus.PatNum)+","
				+"'"+POut.String(satuSehatStatus.ResourceType.ToString())+"',"
				+    POut.Long  (satuSehatStatus.LocalResourceId)+","
				+"'"+POut.String(satuSehatStatus.IhsId)+"',"
				+"'"+POut.String(satuSehatStatus.SyncStatus.ToString())+"',"
				+    POut.DateT (satuSehatStatus.LastSyncAt)+","
				+"'"+POut.String(satuSehatStatus.ErrorMessage)+"',"
				+    POut.Int   (satuSehatStatus.RetryCount)+","
				+    POut.DateT (satuSehatStatus.DateTimeInsert)+")";
			if(useExistingPK || isRandomKeys) {
				Db.NonQ(command);
			}
			else {
				satuSehatStatus.SatuSehatStatusNum=Db.NonQ(command,true,"SatuSehatStatusNum","satuSehatStatus");
			}
			return satuSehatStatus.SatuSehatStatusNum;
		}

		///<summary>Updates one SatuSehatStatus in the database.</summary>
		public static void Update(SatuSehatStatus satuSehatStatus) {
			string command="UPDATE satusehatstatus SET "
				+"PatNum          =  "+POut.Long  (satuSehatStatus.PatNum)+", "
				+"ResourceType    = '"+POut.String(satuSehatStatus.ResourceType.ToString())+"', "
				+"LocalResourceId =  "+POut.Long  (satuSehatStatus.LocalResourceId)+", "
				+"IhsId           = '"+POut.String(satuSehatStatus.IhsId)+"', "
				+"SyncStatus      = '"+POut.String(satuSehatStatus.SyncStatus.ToString())+"', "
				+"LastSyncAt      =  "+POut.DateT (satuSehatStatus.LastSyncAt)+", "
				+"ErrorMessage    = '"+POut.String(satuSehatStatus.ErrorMessage)+"', "
				+"RetryCount      =  "+POut.Int   (satuSehatStatus.RetryCount)+", "
				+"DateTimeInsert  =  "+POut.DateT (satuSehatStatus.DateTimeInsert)+" "
				+"WHERE SatuSehatStatusNum = "+POut.Long(satuSehatStatus.SatuSehatStatusNum);
			Db.NonQ(command);
		}

		///<summary>Updates one SatuSehatStatus in the database.  Uses an old object to compare to, and only alters changed fields.  Returns true if an update occurred.</summary>
		public static bool Update(SatuSehatStatus satuSehatStatus,SatuSehatStatus oldSatuSehatStatus) {
			string command="";
			if(satuSehatStatus.PatNum != oldSatuSehatStatus.PatNum) {
				if(command!="") { command+=",";}
				command+="PatNum = "+POut.Long(satuSehatStatus.PatNum)+"";
			}
			if(satuSehatStatus.ResourceType != oldSatuSehatStatus.ResourceType) {
				if(command!="") { command+=",";}
				command+="ResourceType = '"+POut.String(satuSehatStatus.ResourceType.ToString())+"'";
			}
			if(satuSehatStatus.LocalResourceId != oldSatuSehatStatus.LocalResourceId) {
				if(command!="") { command+=",";}
				command+="LocalResourceId = "+POut.Long(satuSehatStatus.LocalResourceId)+"";
			}
			if(satuSehatStatus.IhsId != oldSatuSehatStatus.IhsId) {
				if(command!="") { command+=",";}
				command+="IhsId = '"+POut.String(satuSehatStatus.IhsId)+"'";
			}
			if(satuSehatStatus.SyncStatus != oldSatuSehatStatus.SyncStatus) {
				if(command!="") { command+=",";}
				command+="SyncStatus = '"+POut.String(satuSehatStatus.SyncStatus.ToString())+"'";
			}
			if(satuSehatStatus.LastSyncAt != oldSatuSehatStatus.LastSyncAt) {
				if(command!="") { command+=",";}
				command+="LastSyncAt = "+POut.DateT(satuSehatStatus.LastSyncAt)+"";
			}
			if(satuSehatStatus.ErrorMessage != oldSatuSehatStatus.ErrorMessage) {
				if(command!="") { command+=",";}
				command+="ErrorMessage = '"+POut.String(satuSehatStatus.ErrorMessage)+"'";
			}
			if(satuSehatStatus.RetryCount != oldSatuSehatStatus.RetryCount) {
				if(command!="") { command+=",";}
				command+="RetryCount = "+POut.Int(satuSehatStatus.RetryCount)+"";
			}
			if(satuSehatStatus.DateTimeInsert != oldSatuSehatStatus.DateTimeInsert) {
				if(command!="") { command+=",";}
				command+="DateTimeInsert = "+POut.DateT(satuSehatStatus.DateTimeInsert)+"";
			}
			if(command=="") {
				return false;
			}
			command="UPDATE satusehatstatus SET "+command
				+" WHERE SatuSehatStatusNum = "+POut.Long(satuSehatStatus.SatuSehatStatusNum);
			Db.NonQ(command);
			return true;
		}

		///<summary>Deletes one SatuSehatStatus from the database.</summary>
		public static void Delete(long satuSehatStatusNum) {
			string command="DELETE FROM satusehatstatus "
				+"WHERE SatuSehatStatusNum = "+POut.Long(satuSehatStatusNum);
			Db.NonQ(command);
		}

		///<summary>Deletes many SatuSehatStatuses from the database.</summary>
		public static void DeleteMany(List<long> listSatuSehatStatusNums) {
			if(listSatuSehatStatusNums==null || listSatuSehatStatusNums.Count==0) {
				return;
			}
			string command="DELETE FROM satusehatstatus "
				+"WHERE SatuSehatStatusNum IN("+string.Join(",",listSatuSehatStatusNums.Select(x => POut.Long(x)))+")";
			Db.NonQ(command);
		}

	}
}
