//This file is automatically generated.
//Do not attempt to make changes to this file because the changes will be erased and overwritten.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Linq;

namespace HelianzBusiness.Crud {
	public class SatuSehatConfigCrud {
		///<summary>Gets one SatuSehatConfig object from the database using the primary key.  Returns null if not found.</summary>
		public static SatuSehatConfig SelectOne(long satuSehatConfigNum) {
			string command="SELECT * FROM satusehatconfig "
				+"WHERE SatuSehatConfigNum = "+POut.Long(satuSehatConfigNum);
			List<SatuSehatConfig> list=TableToList(Db.GetTable(command));
			if(list.Count==0) {
				return null;
			}
			return list[0];
		}

		///<summary>Gets one SatuSehatConfig object from the database using a query.</summary>
		public static SatuSehatConfig SelectOne(string command) {
			if(RemotingClient.MiddleTierRole==MiddleTierRole.ClientMT) {
				throw new ApplicationException("Not allowed to send sql directly.  Rewrite the calling class to not use this query:\r\n"+command);
			}
			List<SatuSehatConfig> list=TableToList(Db.GetTable(command));
			if(list.Count==0) {
				return null;
			}
			return list[0];
		}

		///<summary>Gets a list of SatuSehatConfig objects from the database using a query.</summary>
		public static List<SatuSehatConfig> SelectMany(string command) {
			if(RemotingClient.MiddleTierRole==MiddleTierRole.ClientMT) {
				throw new ApplicationException("Not allowed to send sql directly.  Rewrite the calling class to not use this query:\r\n"+command);
			}
			List<SatuSehatConfig> list=TableToList(Db.GetTable(command));
			return list;
		}

		///<summary>Converts a DataTable to a list of objects.</summary>
		public static List<SatuSehatConfig> TableToList(DataTable table) {
			List<SatuSehatConfig> retVal=new List<SatuSehatConfig>();
			SatuSehatConfig satuSehatConfig;
			foreach(DataRow row in table.Rows) {
				satuSehatConfig=new SatuSehatConfig();
				satuSehatConfig.SatuSehatConfigNum = PIn.Long  (row["SatuSehatConfigNum"].ToString());
				satuSehatConfig.ClientId           = PIn.String(row["ClientId"].ToString());
				satuSehatConfig.ClientSecret       = PIn.String(row["ClientSecret"].ToString());
				satuSehatConfig.OrganizationId     = PIn.String(row["OrganizationId"].ToString());
				string environment=row["Environment"].ToString();
				if(environment=="") {
					satuSehatConfig.Environment=(HelianzBusiness.SatuSehatEnvironment)0;
				}
				else try {
					satuSehatConfig.Environment=(HelianzBusiness.SatuSehatEnvironment)Enum.Parse(typeof(HelianzBusiness.SatuSehatEnvironment),environment);
				}
				catch {
					satuSehatConfig.Environment=(HelianzBusiness.SatuSehatEnvironment)0;
				}
				satuSehatConfig.AccessToken        = PIn.String(row["AccessToken"].ToString());
				satuSehatConfig.TokenExpiresAt     = PIn.DateT (row["TokenExpiresAt"].ToString());
				satuSehatConfig.IsEnabled          = PIn.Bool  (row["IsEnabled"].ToString());
				satuSehatConfig.Note               = PIn.String(row["Note"].ToString());
				satuSehatConfig.LocationId         = PIn.String(row["LocationId"].ToString());
				satuSehatConfig.SyncLockHost       = PIn.String(row["SyncLockHost"].ToString());
				satuSehatConfig.SyncLockAt         = PIn.DateT (row["SyncLockAt"].ToString());
				retVal.Add(satuSehatConfig);
			}
			return retVal;
		}

		///<summary>Converts a list of SatuSehatConfig into a DataTable.</summary>
		public static DataTable ListToTable(List<SatuSehatConfig> listSatuSehatConfigs,string tableName="") {
			if(string.IsNullOrEmpty(tableName)) {
				tableName="SatuSehatConfig";
			}
			DataTable table=new DataTable(tableName);
			table.Columns.Add("SatuSehatConfigNum");
			table.Columns.Add("ClientId");
			table.Columns.Add("ClientSecret");
			table.Columns.Add("OrganizationId");
			table.Columns.Add("Environment");
			table.Columns.Add("AccessToken");
			table.Columns.Add("TokenExpiresAt");
			table.Columns.Add("IsEnabled");
			table.Columns.Add("Note");
			table.Columns.Add("LocationId");
			table.Columns.Add("SyncLockHost");
			table.Columns.Add("SyncLockAt");
			foreach(SatuSehatConfig satuSehatConfig in listSatuSehatConfigs) {
				table.Rows.Add(new object[] {
					POut.Long  (satuSehatConfig.SatuSehatConfigNum),
					POut.String(satuSehatConfig.ClientId),
					POut.String(satuSehatConfig.ClientSecret),
					POut.String(satuSehatConfig.OrganizationId),
					POut.String(satuSehatConfig.Environment.ToString()),
					POut.String(satuSehatConfig.AccessToken),
					POut.DateT (satuSehatConfig.TokenExpiresAt,false),
					POut.Bool  (satuSehatConfig.IsEnabled),
					POut.String(satuSehatConfig.Note),
					POut.String(satuSehatConfig.LocationId),
					POut.String(satuSehatConfig.SyncLockHost),
					POut.DateT (satuSehatConfig.SyncLockAt,false),
				});
			}
			return table;
		}

		///<summary>Inserts one SatuSehatConfig into the database.  Returns the new priKey.</summary>
		public static long Insert(SatuSehatConfig satuSehatConfig) {
			return Insert(satuSehatConfig,false);
		}

		///<summary>Inserts one SatuSehatConfig into the database.  Provides option to use the existing priKey.</summary>
		public static long Insert(SatuSehatConfig satuSehatConfig,bool useExistingPK) {
			if(!useExistingPK && PrefC.RandomKeys) {
				satuSehatConfig.SatuSehatConfigNum=ReplicationServers.GetKey("satusehatconfig","SatuSehatConfigNum");
			}
			string command="INSERT INTO satusehatconfig (";
			if(useExistingPK || PrefC.RandomKeys) {
				command+="SatuSehatConfigNum,";
			}
			command+="ClientId,ClientSecret,OrganizationId,Environment,AccessToken,TokenExpiresAt,IsEnabled,Note,LocationId,SyncLockHost,SyncLockAt) VALUES(";
			if(useExistingPK || PrefC.RandomKeys) {
				command+=POut.Long(satuSehatConfig.SatuSehatConfigNum)+",";
			}
			command+=
				 "'"+POut.String(satuSehatConfig.ClientId)+"',"
				+"'"+POut.String(satuSehatConfig.ClientSecret)+"',"
				+"'"+POut.String(satuSehatConfig.OrganizationId)+"',"
				+"'"+POut.String(satuSehatConfig.Environment.ToString())+"',"
				+"'"+POut.String(satuSehatConfig.AccessToken)+"',"
				+    POut.DateT (satuSehatConfig.TokenExpiresAt)+","
				+    POut.Bool  (satuSehatConfig.IsEnabled)+","
				+"'"+POut.String(satuSehatConfig.Note)+"',"
				+"'"+POut.String(satuSehatConfig.LocationId)+"',"
				+"'"+POut.String(satuSehatConfig.SyncLockHost)+"',"
				+    POut.DateT (satuSehatConfig.SyncLockAt)+")";
			if(useExistingPK || PrefC.RandomKeys) {
				Db.NonQ(command);
			}
			else {
				satuSehatConfig.SatuSehatConfigNum=Db.NonQ(command,true,"SatuSehatConfigNum","satuSehatConfig");
			}
			return satuSehatConfig.SatuSehatConfigNum;
		}

		///<summary>Inserts one SatuSehatConfig into the database.  Returns the new priKey.  Doesn't use the cache.</summary>
		public static long InsertNoCache(SatuSehatConfig satuSehatConfig) {
			return InsertNoCache(satuSehatConfig,false);
		}

		///<summary>Inserts one SatuSehatConfig into the database.  Provides option to use the existing priKey.  Doesn't use the cache.</summary>
		public static long InsertNoCache(SatuSehatConfig satuSehatConfig,bool useExistingPK) {
			bool isRandomKeys=Prefs.GetBoolNoCache(PrefName.RandomPrimaryKeys);
			string command="INSERT INTO satusehatconfig (";
			if(!useExistingPK && isRandomKeys) {
				satuSehatConfig.SatuSehatConfigNum=ReplicationServers.GetKeyNoCache("satusehatconfig","SatuSehatConfigNum");
			}
			if(isRandomKeys || useExistingPK) {
				command+="SatuSehatConfigNum,";
			}
			command+="ClientId,ClientSecret,OrganizationId,Environment,AccessToken,TokenExpiresAt,IsEnabled,Note,LocationId,SyncLockHost,SyncLockAt) VALUES(";
			if(isRandomKeys || useExistingPK) {
				command+=POut.Long(satuSehatConfig.SatuSehatConfigNum)+",";
			}
			command+=
				 "'"+POut.String(satuSehatConfig.ClientId)+"',"
				+"'"+POut.String(satuSehatConfig.ClientSecret)+"',"
				+"'"+POut.String(satuSehatConfig.OrganizationId)+"',"
				+"'"+POut.String(satuSehatConfig.Environment.ToString())+"',"
				+"'"+POut.String(satuSehatConfig.AccessToken)+"',"
				+    POut.DateT (satuSehatConfig.TokenExpiresAt)+","
				+    POut.Bool  (satuSehatConfig.IsEnabled)+","
				+"'"+POut.String(satuSehatConfig.Note)+"',"
				+"'"+POut.String(satuSehatConfig.LocationId)+"',"
				+"'"+POut.String(satuSehatConfig.SyncLockHost)+"',"
				+    POut.DateT (satuSehatConfig.SyncLockAt)+")";
			if(useExistingPK || isRandomKeys) {
				Db.NonQ(command);
			}
			else {
				satuSehatConfig.SatuSehatConfigNum=Db.NonQ(command,true,"SatuSehatConfigNum","satuSehatConfig");
			}
			return satuSehatConfig.SatuSehatConfigNum;
		}

		///<summary>Updates one SatuSehatConfig in the database.</summary>
		public static void Update(SatuSehatConfig satuSehatConfig) {
			string command="UPDATE satusehatconfig SET "
				+"ClientId        = '"+POut.String(satuSehatConfig.ClientId)+"', "
				+"ClientSecret    = '"+POut.String(satuSehatConfig.ClientSecret)+"', "
				+"OrganizationId  = '"+POut.String(satuSehatConfig.OrganizationId)+"', "
				+"Environment     = '"+POut.String(satuSehatConfig.Environment.ToString())+"', "
				+"AccessToken     = '"+POut.String(satuSehatConfig.AccessToken)+"', "
				+"TokenExpiresAt  =  "+POut.DateT (satuSehatConfig.TokenExpiresAt)+", "
				+"IsEnabled       =  "+POut.Bool  (satuSehatConfig.IsEnabled)+", "
			+"Note            = '"+POut.String(satuSehatConfig.Note)+"', "
			+"LocationId      = '"+POut.String(satuSehatConfig.LocationId)+"', "
			+"SyncLockHost    = '"+POut.String(satuSehatConfig.SyncLockHost)+"', "
			+"SyncLockAt      =  "+POut.DateT (satuSehatConfig.SyncLockAt)+" "
				+"WHERE SatuSehatConfigNum = "+POut.Long(satuSehatConfig.SatuSehatConfigNum);
			Db.NonQ(command);
		}

		///<summary>Updates one SatuSehatConfig in the database.  Uses an old object to compare to, and only alters changed fields.  Returns true if an update occurred.</summary>
		public static bool Update(SatuSehatConfig satuSehatConfig,SatuSehatConfig oldSatuSehatConfig) {
			string command="";
			if(satuSehatConfig.ClientId != oldSatuSehatConfig.ClientId) {
				if(command!="") { command+=",";}
				command+="ClientId = '"+POut.String(satuSehatConfig.ClientId)+"'";
			}
			if(satuSehatConfig.ClientSecret != oldSatuSehatConfig.ClientSecret) {
				if(command!="") { command+=",";}
				command+="ClientSecret = '"+POut.String(satuSehatConfig.ClientSecret)+"'";
			}
			if(satuSehatConfig.OrganizationId != oldSatuSehatConfig.OrganizationId) {
				if(command!="") { command+=",";}
				command+="OrganizationId = '"+POut.String(satuSehatConfig.OrganizationId)+"'";
			}
			if(satuSehatConfig.Environment != oldSatuSehatConfig.Environment) {
				if(command!="") { command+=",";}
				command+="Environment = '"+POut.String(satuSehatConfig.Environment.ToString())+"'";
			}
			if(satuSehatConfig.AccessToken != oldSatuSehatConfig.AccessToken) {
				if(command!="") { command+=",";}
				command+="AccessToken = '"+POut.String(satuSehatConfig.AccessToken)+"'";
			}
			if(satuSehatConfig.TokenExpiresAt != oldSatuSehatConfig.TokenExpiresAt) {
				if(command!="") { command+=",";}
				command+="TokenExpiresAt = "+POut.DateT(satuSehatConfig.TokenExpiresAt)+"";
			}
			if(satuSehatConfig.IsEnabled != oldSatuSehatConfig.IsEnabled) {
				if(command!="") { command+=",";}
				command+="IsEnabled = "+POut.Bool(satuSehatConfig.IsEnabled)+"";
			}
			if(satuSehatConfig.Note != oldSatuSehatConfig.Note) {
				if(command!="") { command+=",";}
				command+="Note = '"+POut.String(satuSehatConfig.Note)+"'";
			}
			if(satuSehatConfig.LocationId != oldSatuSehatConfig.LocationId) {
				if(command!="") { command+=",";}
				command+="LocationId = '"+POut.String(satuSehatConfig.LocationId)+"'";
			}
			if(satuSehatConfig.SyncLockHost != oldSatuSehatConfig.SyncLockHost) {
				if(command!="") { command+=",";}
				command+="SyncLockHost = '"+POut.String(satuSehatConfig.SyncLockHost)+"'";
			}
			if(satuSehatConfig.SyncLockAt != oldSatuSehatConfig.SyncLockAt) {
				if(command!="") { command+=",";}
				command+="SyncLockAt = "+POut.DateT(satuSehatConfig.SyncLockAt)+"";
			}
			if(command=="") {
				return false;
			}
			command="UPDATE satusehatconfig SET "+command
				+" WHERE SatuSehatConfigNum = "+POut.Long(satuSehatConfig.SatuSehatConfigNum);
			Db.NonQ(command);
			return true;
		}

		///<summary>Deletes one SatuSehatConfig from the database.</summary>
		public static void Delete(long satuSehatConfigNum) {
			string command="DELETE FROM satusehatconfig "
				+"WHERE SatuSehatConfigNum = "+POut.Long(satuSehatConfigNum);
			Db.NonQ(command);
		}

	}
}
