using System;
using System.Collections.Generic;
using System.IO;

//This file is auto-generated by the 'SecureEmail.CodeGenerator'. Do not change.
namespace HelianzBusiness {
	///<summary></summary>
	public class CreateAccessCodeRequest {

		///<summary></summary>
		public string EmailChainGuid { get; set; }

		///<summary></summary>
		public string EmailAddressGuid { get; set; }

		///<summary></summary>
		public bool ForceCreateNewCode { get; set; }

	}
}
