using System;
using System.Collections.Generic;
using System.IO;

//This file is auto-generated by the 'SecureEmail.CodeGenerator'. Do not change.
namespace HelianzBusiness {
	///<summary></summary>
	public class CreateTemplateRequest {

		///<summary></summary>
		public Template Template { get; set; }

	}
}
