using System;
using System.Collections.Generic;
using System.IO;

//This file is auto-generated by the 'SecureEmail.CodeGenerator'. Do not change.
namespace HelianzBusiness {
	///<summary></summary>
	public class CreateDomainIdentityRequest {

		///<summary>The domain to create an identity for.</summary>
		public string Domain { get; set; }

	}
}
