using System;
using System.Collections.Generic;
using System.IO;

//This file is auto-generated by the 'SecureEmail.CodeGenerator'. Do not change.
namespace HelianzBusiness {
	///<summary></summary>
	public class GetAllTemplatesByAccountResponse {

		///<summary>A dictionary of primary keys to the templates as stored at EmailHosting.</summary>
		public Dictionary<long,Template> DictionaryTemplates { get; set; }

	}
}
