using System;
using System.Collections.Generic;
using System.IO;

//This file is auto-generated by the 'SecureEmail.CodeGenerator'. Do not change.
namespace HelianzBusiness {
	///<summary></summary>
	public class GetDomainDKIMTokensResponse {

		///<summary>A list of the tokens that need to be added into their DNS as CNAME records.</summary>
		public List<string> ListCNAMERecords { get; set; }

	}
}
