using System;
using System.Collections.Generic;
using System.IO;

//This file is auto-generated by the 'SecureEmail.CodeGenerator'. Do not change.
namespace HelianzBusiness {
	///<summary></summary>
	public class GetEmailResponse {

		///<summary></summary>
		public EmailResource Email { get; set; }

		///<summary></summary>
		public EmailAddressResource ChainOwner { get; set; }

		///<summary></summary>
		public List<EmailAddressResource> ListEmailAddresses { get; set; }

	}
}
