using System;
using System.Collections.Generic;
using System.IO;

//This file is auto-generated by the 'SecureEmail.CodeGenerator'. Do not change.
namespace HelianzBusiness {
	///<summary></summary>
	public class GetIdentityResponse {

		///<summary></summary>
		public IdentityResource IdentityResource { get; set; }

	}
}
