using System;
using System.Collections.Generic;
using System.IO;

//This file is auto-generated by the 'SecureEmail.CodeGenerator'. Do not change.
namespace HelianzBusiness {
	///<summary></summary>
	public class ValidateAccessCodeResponse {

		///<summary>The AccessCodeGuid.</summary>
		public string ApiToken { get; set; }

		///<summary></summary>
		public string EmailAddress { get; set; }

	}
}
