using System;
using System.Collections.Generic;
using System.IO;

//This file is auto-generated by the 'SecureEmail.CodeGenerator'. Do not change.
namespace HelianzBusiness {
	///<summary></summary>
	public class ValidateAccessCodeRequest {

		///<summary></summary>
		public string AccessCode { get; set; }

		///<summary></summary>
		public string AccessCodeGuid { get; set; }

	}
}
