.\"                                      Hey, EMACS: -*- nroff -*-
.\"
.\"
.TH nant 1 "2005-05-16"
.SH "NAME"
Helianz \- Open Source Practice Management
.SH "SYNOPOSIS"
.B helianz
.B Helianz
is the first dental software written for the .NET framework
.SH "SEE ALSO"
Helianz web site
.UR http://www.helianz.com/
http://www.helianz.com/
.UE
.LP
Man page by Frederik Carlier, made available under the same terms as Helianz
